backend:
  name: git-gateway
  branch: api-update # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: "tour"
    label: "Tour Entry"
    folder: "src/pages/tour"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Location", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}